src/java/entities/Scheduledhours.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Mateusz Aniolek
 */
@Entity
@Table(name = "SCHEDULEDHOURS")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Scheduledhours.findAll", query = "SELECT s FROM Scheduledhours s"),
    @NamedQuery(name = "Scheduledhours.findById", query = "SELECT s FROM Scheduledhours s WHERE s.id = :id"),
    @NamedQuery(name = "Scheduledhours.findByUserid", query = "SELECT s FROM Scheduledhours s WHERE s.userid = :userid"),
    @NamedQuery(name = "Scheduledhours.findByWeekday", query = "SELECT s FROM Scheduledhours s WHERE s.weekday = :weekday"),
    @NamedQuery(name = "Scheduledhours.findByStarthour", query = "SELECT s FROM Scheduledhours s WHERE s.starthour = :starthour"),
    @NamedQuery(name = "Scheduledhours.findByEndhour", query = "SELECT s FROM Scheduledhours s WHERE s.endhour = :endhour")})
public class Scheduledhours implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
//    @Basic(optional = false)
//    @NotNull
    @Column(name = "ID", insertable = false)
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Column(name = "USERID")
    private int userid;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 15)
    @Column(name = "WEEKDAY")
    private String weekday;
    @Basic(optional = false)
    @NotNull
    @Column(name = "STARTHOUR")
    @Temporal(TemporalType.TIME)
    private Date starthour;
    @Basic(optional = false)
    @NotNull
    @Column(name = "ENDHOUR")
    @Temporal(TemporalType.TIME)
    private Date endhour;

    /**
     *
     */
    public Scheduledhours() {
    }

    /**
     *
     * @param id
     */
    public Scheduledhours(Integer id) {
        this.id = id;
    }

    /**
     *
     * @param id
     * @param userid
     * @param weekday
     * @param starthour
     * @param endhour
     */
    public Scheduledhours(Integer id, int userid, String weekday, Date starthour, Date endhour) {
        this.id = id;
        this.userid = userid;
        this.weekday = weekday;
        this.starthour = starthour;
        this.endhour = endhour;
    }

    /**
     *
     * @return
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public int getUserid() {
        return userid;
    }

    /**
     *
     * @param userid
     */
    public void setUserid(int userid) {
        this.userid = userid;
    }

    /**
     *
     * @return
     */
    public String getWeekday() {
        return weekday;
    }

    /**
     *
     * @param weekday
     */
    public void setWeekday(String weekday) {
        this.weekday = weekday;
    }

    /**
     *
     * @return
     */
    public Date getStarthour() {
        return starthour;
    }

    /**
     *
     * @param starthour
     */
    public void setStarthour(Date starthour) {
        this.starthour = starthour;
    }

    /**
     *
     * @return
     */
    public Date getEndhour() {
        return endhour;
    }

    /**
     *
     * @param endhour
     */
    public void setEndhour(Date endhour) {
        this.endhour = endhour;
    }

    /**
     *
     * @return
     */
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    /**
     *
     * @param object
     * @return
     */
    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Scheduledhours)) {
            return false;
        }
        Scheduledhours other = (Scheduledhours) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    /**
     *
     * @return
     */
    @Override
    public String toString() {
        return "entities.Scheduledhours[ id=" + id + " ]";
    }

}

src/java/controller/ScheduledhoursController.java
package controller;

import entities.Scheduledhours;
import controller.util.JsfUtil;
import controller.util.PaginationHelper;
import jpa.beans.ScheduledhoursFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

/**
 *
 * @author Mateusz Aniolek
 */
@Named("scheduledhoursController")
@SessionScoped
public class ScheduledhoursController implements Serializable {

    private Scheduledhours current;
    private DataModel items = null;
    @EJB
    private jpa.beans.ScheduledhoursFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    /**
     *
     */
    public ScheduledhoursController() {
    }

    /**
     *
     * @return
     */
    public Scheduledhours getSelected() {
        if (current == null) {
            current = new Scheduledhours();
            selectedItemIndex = -1;
        }
        return current;
    }

    private ScheduledhoursFacade getFacade() {
        return ejbFacade;
    }

    /**
     *
     * @return
     */
    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    /**
     *
     * @return
     */
    public String prepareList() {
        recreateModel();
        return "List";
    }

    /**
     *
     * @return
     */
    public String prepareView() {
        current = (Scheduledhours) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    /**
     *
     * @return
     */
    public String prepareCreate() {
        current = new Scheduledhours();
        selectedItemIndex = -1;
        return "Create";
    }

    /**
     *
     * @return
     */
    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("ScheduledhoursCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    /**
     *
     * @return
     */
    public String prepareEdit() {
        current = (Scheduledhours) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    /**
     *
     * @return
     */
    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("ScheduledhoursUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    /**
     *
     * @return
     */
    public String destroy() {
        current = (Scheduledhours) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    /**
     *
     * @return
     */
    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("ScheduledhoursDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    /**
     *
     * @return
     */
    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    /**
     *
     * @return
     */
    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    /**
     *
     * @return
     */
    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    /**
     *
     * @return
     */
    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    /**
     *
     * @return
     */
    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    /**
     *
     * @param id
     * @return
     */
    public Scheduledhours getScheduledhours(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    /**
     *
     */
    @FacesConverter(forClass = Scheduledhours.class)
    public static class ScheduledhoursControllerConverter implements Converter {

        /**
         *
         * @param facesContext
         * @param component
         * @param value
         * @return
         */
        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ScheduledhoursController controller = (ScheduledhoursController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "scheduledhoursController");
            return controller.getScheduledhours(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        /**
         *
         * @param facesContext
         * @param component
         * @param object
         * @return
         */
        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Scheduledhours) {
                Scheduledhours o = (Scheduledhours) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Scheduledhours.class.getName());
            }
        }

    }

}

web/scheduledhours/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="body">
            <div class="row marketing">
                <div class="col-lg-12">
                    <h3>Create</h3>
                    <h:form>
                        <div class="pull-right">
                            <h:commandLink action="#{scheduledhoursController.prepareList}" styleClass="btn btn-info" value="#{bundle.CreateScheduledhoursShowAllLink}"/>
                        </div>
                    </h:form>
                    <br/>
                    <br/>
                    <h:panelGroup id="messagePanel" layout="block">
                        <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                    </h:panelGroup>
                    <h:form>
                        <h:panelGrid columns="2" styleClass="table">
                            <h:outputLabel value="#{bundle.CreateScheduledhoursLabel_userid}" for="userid" />
                            <h:selectOneMenu value="#{scheduledhoursController.selected.userid}" styleClass="form-control" id="userid" title="#{bundle.CreateScheduledhoursTitle_userid}" required="true" requiredMessage="#{bundle.CreateScheduledhoursRequiredMessage_userid}">
                                <f:selectItems value="#{usersList.users}" var="user" itemValue="#{user.id}" itemLabel="#{user.login}" />
                            </h:selectOneMenu>
                            <h:outputLabel value="#{bundle.CreateScheduledhoursLabel_weekday}" for="weekday" />
                            <h:selectOneMenu styleClass="form-control" id="weekday" value="#{scheduledhoursController.selected.weekday}" title="#{bundle.CreateScheduledhoursTitle_weekday}" required="true" requiredMessage="#{bundle.CreateScheduledhoursRequiredMessage_weekday}">
                                <f:selectItem itemValue="monday" itemLabel="Monday"/>
                                <f:selectItem itemValue="tuesday" itemLabel="Tuesday"/>
                                <f:selectItem itemValue="wednesday" itemLabel="Wednesday"/>
                                <f:selectItem itemValue="thursday" itemLabel="Thursday"/>
                                <f:selectItem itemValue="friday" itemLabel="Friday"/>
                                <f:selectItem itemValue="saturday" itemLabel="Saturday"/>
                                <f:selectItem itemValue="sunday" itemLabel="Sunday"/>
                            </h:selectOneMenu>
                            <h:outputLabel value="#{bundle.CreateScheduledhoursLabel_starthour}" for="starthour" />
                            <h:selectOneMenu id="starthour" styleClass="form-control" value="#{scheduledhoursController.selected.starthour}" title="#{bundle.CreateScheduledhoursTitle_starthour}" required="true" requiredMessage="#{bundle.CreateScheduledhoursRequiredMessage_starthour}">
                                <f:selectItem itemValue="7:00" itemLabel="7:00"/>
                                <f:selectItem itemValue="8:00" itemLabel="8:00"/>
                                <f:selectItem itemValue="9:00" itemLabel="9:00"/>
                                <f:selectItem itemValue="10:00" itemLabel="10:00"/>
                                <f:selectItem itemValue="11:00" itemLabel="11:00"/>
                                <f:selectItem itemValue="12:00" itemLabel="12:00"/>
                                <f:selectItem itemValue="13:00" itemLabel="13:00"/>
                                <f:selectItem itemValue="14:00" itemLabel="14:00"/>
                                <f:selectItem itemValue="15:00" itemLabel="15:00"/>
                                <f:selectItem itemValue="16:00" itemLabel="16:00"/>
                                <f:selectItem itemValue="17:00" itemLabel="17:00"/>
                                <f:selectItem itemValue="18:00" itemLabel="18:00"/>
                                <f:selectItem itemValue="19:00" itemLabel="19:00"/>
                                <f:selectItem itemValue="20:00" itemLabel="20:00"/>
                                <f:convertDateTime pattern="HH:mm"/>
                            </h:selectOneMenu>
                            <h:outputLabel value="#{bundle.CreateScheduledhoursLabel_endhour}" for="endhour" />
                            <h:selectOneMenu id="endhour" styleClass="form-control" value="#{scheduledhoursController.selected.endhour}" title="#{bundle.CreateScheduledhoursTitle_endhour}" required="true" requiredMessage="#{bundle.CreateScheduledhoursRequiredMessage_endhour}">
                                <f:selectItem itemValue="7:00" itemLabel="7:00"/>
                                <f:selectItem itemValue="8:00" itemLabel="8:00"/>
                                <f:selectItem itemValue="9:00" itemLabel="9:00"/>
                                <f:selectItem itemValue="10:00" itemLabel="10:00"/>
                                <f:selectItem itemValue="11:00" itemLabel="11:00"/>
                                <f:selectItem itemValue="12:00" itemLabel="12:00"/>
                                <f:selectItem itemValue="13:00" itemLabel="13:00"/>
                                <f:selectItem itemValue="14:00" itemLabel="14:00"/>
                                <f:selectItem itemValue="15:00" itemLabel="15:00"/>
                                <f:selectItem itemValue="16:00" itemLabel="16:00"/>
                                <f:selectItem itemValue="17:00" itemLabel="17:00"/>
                                <f:selectItem itemValue="18:00" itemLabel="18:00"/>
                                <f:selectItem itemValue="19:00" itemLabel="19:00"/>
                                <f:selectItem itemValue="20:00" itemLabel="20:00"/>
                                <f:convertDateTime pattern="HH:mm"/>
                            </h:selectOneMenu>

                        </h:panelGrid>
                        <br />
                        <h:commandLink action="#{scheduledhoursController.create}" value="#{bundle.CreateScheduledhoursSaveLink}" />
                        <br />
                    </h:form>
                </div>
            </div>
        </ui:define>
    </ui:composition>

</html>

web/scheduledhours/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="body">
            <div class="row marketing">
                <div class="col-lg-12">
                    <h3>Edit</h3>
                    <h:form>
                    <div class="pull-right">
                        <h:commandLink action="#{scheduledhoursController.prepareList}" styleClass="btn btn-info" value="#{bundle.EditScheduledhoursShowAllLink}"/>
                    </div>
                    </h:form>
                    <br/>
                    <br/>
                    <h:panelGroup id="messagePanel" layout="block">
                        <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                    </h:panelGroup>
                    <h:form>
                        <h:panelGrid columns="2" styleClass="table">
                            <h:outputLabel value="#{bundle.EditScheduledhoursLabel_userid}" for="userid" />
                            <h:selectOneMenu value="#{scheduledhoursController.selected.userid}" styleClass="form-control" id="userid" title="#{bundle.CreateScheduledhoursTitle_userid}" required="true" requiredMessage="#{bundle.CreateScheduledhoursRequiredMessage_userid}">
                                <f:selectItems value="#{usersList.users}" var="user" itemValue="#{user.id}" itemLabel="#{user.login}" />
                            </h:selectOneMenu>
                            <h:outputLabel value="#{bundle.EditScheduledhoursLabel_weekday}" for="weekday" />
                            <h:selectOneMenu styleClass="form-control" id="weekday" value="#{scheduledhoursController.selected.weekday}" title="#{bundle.CreateScheduledhoursTitle_weekday}" required="true" requiredMessage="#{bundle.CreateScheduledhoursRequiredMessage_weekday}">
                                <f:selectItem itemValue="monday" itemLabel="Monday"/>
                                <f:selectItem itemValue="tuesday" itemLabel="Tuesday"/>
                                <f:selectItem itemValue="wednesday" itemLabel="Wednesday"/>
                                <f:selectItem itemValue="thursday" itemLabel="Thursday"/>
                                <f:selectItem itemValue="friday" itemLabel="Friday"/>
                                <f:selectItem itemValue="saturday" itemLabel="Saturday"/>
                                <f:selectItem itemValue="sunday" itemLabel="Sunday"/>
                            </h:selectOneMenu>
                            <h:outputLabel value="#{bundle.EditScheduledhoursLabel_starthour}" for="starthour" />
                            <h:selectOneMenu id="starthour" styleClass="form-control" value="#{scheduledhoursController.selected.starthour}" title="#{bundle.CreateScheduledhoursTitle_starthour}" required="true" requiredMessage="#{bundle.CreateScheduledhoursRequiredMessage_starthour}">
                                <f:selectItem itemValue="7:00" itemLabel="7:00"/>
                                <f:selectItem itemValue="8:00" itemLabel="8:00"/>
                                <f:selectItem itemValue="9:00" itemLabel="9:00"/>
                                <f:selectItem itemValue="10:00" itemLabel="10:00"/>
                                <f:selectItem itemValue="11:00" itemLabel="11:00"/>
                                <f:selectItem itemValue="12:00" itemLabel="12:00"/>
                                <f:selectItem itemValue="13:00" itemLabel="13:00"/>
                                <f:selectItem itemValue="14:00" itemLabel="14:00"/>
                                <f:selectItem itemValue="15:00" itemLabel="15:00"/>
                                <f:selectItem itemValue="16:00" itemLabel="16:00"/>
                                <f:selectItem itemValue="17:00" itemLabel="17:00"/>
                                <f:selectItem itemValue="18:00" itemLabel="18:00"/>
                                <f:selectItem itemValue="19:00" itemLabel="19:00"/>
                                <f:selectItem itemValue="20:00" itemLabel="20:00"/>
                                <f:convertDateTime pattern="HH:mm"/>
                            </h:selectOneMenu>
                            <h:outputLabel value="#{bundle.EditScheduledhoursLabel_endhour}" for="endhour" />
                            <h:selectOneMenu id="endhour" styleClass="form-control" value="#{scheduledhoursController.selected.endhour}" title="#{bundle.CreateScheduledhoursTitle_endhour}" required="true" requiredMessage="#{bundle.CreateScheduledhoursRequiredMessage_endhour}">
                                <f:selectItem itemValue="7:00" itemLabel="7:00"/>
                                <f:selectItem itemValue="8:00" itemLabel="8:00"/>
                                <f:selectItem itemValue="9:00" itemLabel="9:00"/>
                                <f:selectItem itemValue="10:00" itemLabel="10:00"/>
                                <f:selectItem itemValue="11:00" itemLabel="11:00"/>
                                <f:selectItem itemValue="12:00" itemLabel="12:00"/>
                                <f:selectItem itemValue="13:00" itemLabel="13:00"/>
                                <f:selectItem itemValue="14:00" itemLabel="14:00"/>
                                <f:selectItem itemValue="15:00" itemLabel="15:00"/>
                                <f:selectItem itemValue="16:00" itemLabel="16:00"/>
                                <f:selectItem itemValue="17:00" itemLabel="17:00"/>
                                <f:selectItem itemValue="18:00" itemLabel="18:00"/>
                                <f:selectItem itemValue="19:00" itemLabel="19:00"/>
                                <f:selectItem itemValue="20:00" itemLabel="20:00"/>
                                <f:convertDateTime pattern="HH:mm"/>
                            </h:selectOneMenu>
                        </h:panelGrid>
                        <h:commandLink action="#{scheduledhoursController.update}" value="#{bundle.EditScheduledhoursSaveLink}"/>
                        <br />
                    </h:form>
                </div>
            </div>
        </ui:define>
    </ui:composition>

</html>

web/scheduledhours/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="body">

            <div class="row marketing">
                <div class="col-lg-12">
                    <h3>List</h3>
                    <h:form>
                    <div class="pull-right">
                        <h:commandLink action="#{scheduledhoursController.prepareCreate}" styleClass="btn btn-info" value="#{bundle.ListScheduledhoursCreateLink}"/>
                    </div>
                    </h:form>
                    <br/>
                    <br/>
                    <h:form styleClass="jsfcrud_list_form">
                        <h:panelGroup id="messagePanel" layout="block">
                            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                        </h:panelGroup>
                        <h:outputText escape="false" value="#{bundle.ListScheduledhoursEmpty}" rendered="#{scheduledhoursController.items.rowCount == 0}"/>
                        <h:panelGroup rendered="#{scheduledhoursController.items.rowCount > 0}">
                            <h:outputText value="#{scheduledhoursController.pagination.pageFirstItem + 1}..#{scheduledhoursController.pagination.pageLastItem + 1}/#{scheduledhoursController.pagination.itemsCount}"/>&nbsp;
                            <h:commandLink action="#{scheduledhoursController.previous}" value="#{bundle.Previous} #{scheduledhoursController.pagination.pageSize}" rendered="#{scheduledhoursController.pagination.hasPreviousPage}"/>&nbsp;
                            <h:commandLink action="#{scheduledhoursController.next}" value="#{bundle.Next} #{scheduledhoursController.pagination.pageSize}" rendered="#{scheduledhoursController.pagination.hasNextPage}"/>&nbsp;
                            <h:dataTable value="#{scheduledhoursController.items}" var="item" styleClass="table">
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="#{bundle.ListScheduledhoursTitle_id}"/>
                                    </f:facet>
                                    <h:outputText value="#{item.id}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Username"/>
                                    </f:facet>
                                    <h:outputText value="#{usersList.getUser(item.userid)}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="#{bundle.ListScheduledhoursTitle_weekday}"/>
                                    </f:facet>
                                    <h:outputText value="#{item.weekday}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="#{bundle.ListScheduledhoursTitle_starthour}"/>
                                    </f:facet>
                                    <h:outputText value="#{item.starthour}">
                                        <f:convertDateTime pattern="HH:mm" />
                                    </h:outputText>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="#{bundle.ListScheduledhoursTitle_endhour}"/>
                                    </f:facet>
                                    <h:outputText value="#{item.endhour}">
                                        <f:convertDateTime pattern="HH:mm" />
                                    </h:outputText>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="&nbsp;"/>
                                    </f:facet>
                                    <h:commandLink action="#{scheduledhoursController.prepareView}" value="#{bundle.ListScheduledhoursViewLink}"/>
                                    <h:outputText value=" "/>
                                    <h:commandLink action="#{scheduledhoursController.prepareEdit}" value="#{bundle.ListScheduledhoursEditLink}"/>
                                    <h:outputText value=" "/>
                                    <h:commandLink action="#{scheduledhoursController.destroy}" value="#{bundle.ListScheduledhoursDestroyLink}"/>
                                </h:column>
                            </h:dataTable>
                        </h:panelGroup>

                    </h:form>
                </div>
            </div>
        </ui:define>
    </ui:composition>

</html>